export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            width: "100%",
            height: "5rem",
            backgroundColor: "grey",
            textAlign: "center",
            fontSize: "50px",
            marginBottom: "100px",
          }}
        >
          HEADER
        </header>
        {children}

        <footer
          style={{
            width: "100%",
            height: "4rem",
            backgroundColor: "red",
            textAlign: "center",
            fontSize: "50px",
            marginTop: "100px",
          }}
        >
          FOOTER
        </footer>
      </body>
    </html>
  );
}
